# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TempBeneficiaries',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('index', models.BigIntegerField(null=True, blank=True)),
                ('project_id', models.TextField(null=True, blank=True)),
                ('report_id', models.TextField(null=True, blank=True)),
                ('beneficiary_id', models.TextField(null=True, blank=True)),
                ('cluster_id', models.TextField(null=True, blank=True)),
                ('cluster', models.TextField(null=True, blank=True)),
                ('focal_point_name', models.TextField(null=True, blank=True)),
                ('focal_point_phone', models.TextField(null=True, blank=True)),
                ('focal_point_email', models.TextField(null=True, blank=True)),
                ('mpc_purpose_cluster_id', models.FloatField(null=True, blank=True)),
                ('mpc_purpose_type_name', models.FloatField(null=True, blank=True)),
                ('organization', models.TextField(null=True, blank=True)),
                ('implementing_partners', models.TextField(null=True, blank=True)),
                ('project_hrp_code', models.TextField(null=True, blank=True)),
                ('project_code', models.TextField(null=True, blank=True)),
                ('project_title', models.TextField(null=True, blank=True)),
                ('project_start_date', models.TextField(null=True, blank=True)),
                ('project_end_date', models.TextField(null=True, blank=True)),
                ('donor', models.TextField(null=True, blank=True)),
                ('report_month_number', models.BigIntegerField(null=True, blank=True)),
                ('report_month', models.TextField(null=True, blank=True)),
                ('report_year', models.BigIntegerField(null=True, blank=True)),
                ('reporting_period', models.TextField(null=True, blank=True)),
                ('admin0pcode', models.TextField(null=True, blank=True)),
                ('admin0name', models.TextField(null=True, blank=True)),
                ('admin1pcode', models.BigIntegerField(null=True, blank=True)),
                ('admin1name', models.TextField(null=True, blank=True)),
                ('admin2pcode', models.BigIntegerField(null=True, blank=True)),
                ('admin2name', models.TextField(null=True, blank=True)),
                ('admin3pcode', models.TextField(null=True, blank=True)),
                ('admin3name', models.TextField(null=True, blank=True)),
                ('admin4pcode', models.TextField(null=True, blank=True)),
                ('admin4name', models.TextField(null=True, blank=True)),
                ('admin5pcode', models.FloatField(null=True, blank=True)),
                ('admin5name', models.FloatField(null=True, blank=True)),
                ('conflict', models.NullBooleanField()),
                ('site_id', models.TextField(null=True, blank=True)),
                ('site_class', models.TextField(null=True, blank=True)),
                ('site_status', models.TextField(null=True, blank=True)),
                ('site_hub_id', models.FloatField(null=True, blank=True)),
                ('site_hub_name', models.FloatField(null=True, blank=True)),
                ('site_implementation_name', models.FloatField(null=True, blank=True)),
                ('site_type_name', models.TextField(null=True, blank=True)),
                ('site_name', models.TextField(null=True, blank=True)),
                ('category_type_id', models.FloatField(null=True, blank=True)),
                ('category_type_name', models.FloatField(null=True, blank=True)),
                ('beneficiary_type_id', models.TextField(null=True, blank=True)),
                ('beneficiary_type_name', models.TextField(null=True, blank=True)),
                ('beneficiary_category_name', models.FloatField(null=True, blank=True)),
                ('strategic_objective_id', models.TextField(null=True, blank=True)),
                ('strategic_objective_name', models.TextField(null=True, blank=True)),
                ('strategic_objective_description', models.TextField(null=True, blank=True)),
                ('sector_objective_id', models.TextField(null=True, blank=True)),
                ('sector_objective_name', models.TextField(null=True, blank=True)),
                ('sector_objective_description', models.TextField(null=True, blank=True)),
                ('activity_type_id', models.TextField(null=True, blank=True)),
                ('activity_type_name', models.TextField(null=True, blank=True)),
                ('activity_description_id', models.TextField(null=True, blank=True)),
                ('activity_description_name', models.TextField(null=True, blank=True)),
                ('activity_detail_id', models.TextField(null=True, blank=True)),
                ('activity_detail_name', models.TextField(null=True, blank=True)),
                ('indicator_id', models.TextField(null=True, blank=True)),
                ('indicator_name', models.TextField(null=True, blank=True)),
                ('activity_status_id', models.FloatField(null=True, blank=True)),
                ('activity_status_name', models.FloatField(null=True, blank=True)),
                ('delivery_type_id', models.TextField(null=True, blank=True)),
                ('delivery_type_name', models.TextField(null=True, blank=True)),
                ('distribution_status', models.TextField(null=True, blank=True)),
                ('distribution_start_date', models.TextField(null=True, blank=True)),
                ('distribution_end_date', models.TextField(null=True, blank=True)),
                ('partial_kits', models.FloatField(null=True, blank=True)),
                ('kit_details', models.FloatField(null=True, blank=True)),
                ('units', models.BigIntegerField(null=True, blank=True)),
                ('unit_type_id', models.TextField(null=True, blank=True)),
                ('unit_type_name', models.TextField(null=True, blank=True)),
                ('transfer_type_value', models.FloatField(null=True, blank=True)),
                ('mpc_delivery_type_id', models.TextField(null=True, blank=True)),
                ('mpc_delivery_type_name', models.TextField(null=True, blank=True)),
                ('mpc_mechanism_type_id', models.FloatField(null=True, blank=True)),
                ('mpc_mechanism_type_name', models.FloatField(null=True, blank=True)),
                ('package_type_id', models.FloatField(null=True, blank=True)),
                ('households', models.BigIntegerField(null=True, blank=True)),
                ('families', models.BigIntegerField(null=True, blank=True)),
                ('boys', models.BigIntegerField(null=True, blank=True)),
                ('girls', models.BigIntegerField(null=True, blank=True)),
                ('men', models.BigIntegerField(null=True, blank=True)),
                ('women', models.BigIntegerField(null=True, blank=True)),
                ('elderly_men', models.BigIntegerField(null=True, blank=True)),
                ('elderly_women', models.BigIntegerField(null=True, blank=True)),
                ('total', models.BigIntegerField(null=True, blank=True)),
                ('admin1lng', models.FloatField(null=True, blank=True)),
                ('admin1lat', models.FloatField(null=True, blank=True)),
                ('admin2lng', models.FloatField(null=True, blank=True)),
                ('admin2lat', models.FloatField(null=True, blank=True)),
                ('admin3lng', models.FloatField(null=True, blank=True)),
                ('admin3lat', models.FloatField(null=True, blank=True)),
                ('admin4lng', models.FloatField(null=True, blank=True)),
                ('admin4lat', models.FloatField(null=True, blank=True)),
                ('admin5lng', models.FloatField(null=True, blank=True)),
                ('admin5lat', models.FloatField(null=True, blank=True)),
                ('site_lng', models.FloatField(null=True, blank=True)),
                ('site_lat', models.FloatField(null=True, blank=True)),
                ('updatedat', models.TextField(null=True, blank=True)),
                ('createdat', models.TextField(null=True, blank=True)),
            ],
            options={
                'db_table': '"temporary"."temp_beneficiaries"',
                'managed': False,
            },
        ),
    ]
